#cloud-config
package_update: true
package_upgrade: true
write_files:
  - path: /etc/networkd-dispatcher/routable.d/50-masq
    owner: root:root
    permissions: '0755'
    content: |
      #!/bin/sh

      /bin/echo 1 > /proc/sys/net/ipv4/ip_forward
      /sbin/iptables -t nat -A POSTROUTING -s '172.18.64.0/22' -o eth0 -j MASQUERADE
